# Generated by Django 4.2 on 2023-04-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='hand_out_conditionn',
            new_name='hand_out_condition',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='returned_conditionn',
            new_name='returned_condition',
        ),
    ]
