# Generated by Django 4.2 on 2023-04-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_hand_out_conditionn_asset_hand_out_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='returned_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
